---
title: "Coffee & Weather"
subtitle: "A Springboard Capstone Project Proposal"
author: "Edward Zavertyaev"
output: 
  html_document:
    self_contained: no
    smart: false
---

### THE PROBLEM

**Owners of independent coffee shops often don't know why certain drinks are popular on certain days.** 

Unlike the big chains with their large R&D departments, these small business owners don't have the resources to investigate this puzzle.

What makes a drink sell? Do its contents---espresso, water, milk, chocolate, or anything else---influence this? Or do some other, external variables play a role?

Anecdotally, we know that coffee is a comfort beverage. Obviously, an iced americano goes well with a hot summer day, just as a hot latte lends itself nicely to staying inside a cozy coffee shop in the dead of winter.

**What if demand for coffee beverages has something to do with the weather?**

Big companies in the coffee market seem to think so. Dunkin' Donuts has [blamed](https://www.usatoday.com/story/money/business/2014/04/24/dunkin-donuts-earnings-stormy-weather/8086615/) the weather on poor sales, and Starbucks [engages](http://www.weatherunlocked.com/media/1096/the-complete-guide-to-weather-based-marketing.pdf) in weather-triggered marketing.

Interestingly, there are [several](https://enterprisesolutions.accuweather.com/assets/documents/AccuWeather_D3_Solutions.pdf) [commercial](http://www.skymosity.com/articles/coffee-and-weather.pdf) [solutions](http://www.weatherunlocked.com/media/1096/the-complete-guide-to-weather-based-marketing.pdf) that specialize in taking a business' sales or ad campaign data and combining it with local weather data to produce insight. In my capstone project, I will attempt to do the same. 

I will take sales data from a neighborhood coffee shop and combine it with historical weather data from a local weather station. Then, I will investigate whether there are any relationships between weather condition variables and beverage contents and preparation procedures.


### THE CLIENT

The client is an independently owned coffee shop in Canada.[^1] The client makes for a great case study because they're located in a climate with clearly defined seasons.

My analysis will have implications for the following aspects of the client's day-to-day operations:

-	**Demand planning.** Having insight into the effects of weather variables on product demand, the client will be able to adjust how they manage stock. For example, they could order less milk if they expect less demand for milk-based beverages.

-	**Product development.** Knowing how weather conditions influence beverage preferences, the client may decide to adjust the current product selection or create new products.

-	**Marketing.** Aware of just which products customers want to buy in certain weather conditions, the client may adjust what---and how---they market. Weather-based marketing won't just involve deciding what witty message will work well on that sidewalk sign outside the door that day. For instance, the client may want to collect their customers' email addresses to produce weather-trigged marketing campaigns or send out a timely call to action on the business' social media accounts.

[^1]: To respect the conditions of my non-disclosure agreement with the business, I will not name or otherwise make the business identifiable.


### THE DATA

To complete this project, I will combine two sets of data:

1. client-supplied data on orders, generated by a cloud-based cash register system, and

2. historical daily weather data from the Government of Canada.

The client has given me over 400 \*.csv files. Each file represents a day of operation and contains hundreds of lines with information on every order made that day, including products purchased, payment information, and time of order (HH:MM).

I will download daily[^2] weather data for the client's location from the Government of Canada's website. For an example, see [this](http://climate.weather.gc.ca/climate_data/daily_data_e.html?hlyRange=2013-02-13%7C2017-11-27&dlyRange=2013-02-14%7C2017-11-27&mlyRange=%7C&StationID=51157&Prov=QC&urlExtension=_e.html&searchType=stnProx&optLimit=yearRange&Month=11&Day=27&StartYear=2014&EndYear=2017&Year=2017&selRowPerPage=25&Line=1&txtRadius=25&optProxType=city&selCity=45%7C31%7C73%7C39%7CMontr%C3%A9al&selPark=&txtCentralLatDeg=&txtCentralLatMin=0&txtCentralLatSec=0&txtCentralLongDeg=&txtCentralLongMin=0&txtCentralLongSec=0&timeframe=2) daily data report for November 2017.

[^2]: You may notice that the client's data and the weather data are at different levels of precision. While hourly weather data is [available](http://climate.weather.gc.ca/climate_data/hourly_data_e.html?hlyRange=1994-02-01%7C2017-11-27&dlyRange=1994-07-26%7C2017-11-27&mlyRange=%7C&StationID=10761&Prov=QC&urlExtension=_e.html&searchType=stnProx&optLimit=specDate&Month=11&Day=27&StartYear=1840&EndYear=2017&Year=2017&selRowPerPage=25&Line=1&txtRadius=25&optProxType=navLink&txtLatDecDeg=45.467777777778&txtLongDecDeg=73.741666666667&timeframe=1), I opted to use daily data instead. Combining hourly sales with hourly weather data would not work well because the client's business does not operate 24/7. This would leave large gaps in the weather data, impacting hour-to-hour changes. (It wouldn't be correct to compare the hour-to-hour change between 10 AM and 11 AM if we're also factoring in the change between 7 PM and 7 AM the next day---hours when the shop is closed---as just one hour.) Given this, I would have to choose a level of precision where I can ensure continuity of data for both sales and weather variables. Therefore, one goal of my project will be to change the granularity of all data from hours and minutes to days.


### THE APPROACH

Preliminarily, I outline the following steps necessary to solve the problem:

1. Extract the client-supplied data from hundreds of \*.csv files into a data frame of *orders*, where each observation is *a unique order* made at the client's business at HH:MM on a given day.

2. Create a codebook for *beverage products*, coding each product on the menu according to a set of dummy variables (contains espresso, contains milk, hot or cold, milk frothed or not, etc.).

3. Transform the *orders* data frame into a data frame of *daily sales*.

4. Download and compile *weather data* into a single data frame, and combine it with *daily sales*.

5. Perform Data Science Magic to uncover whether there are any relationships among variables and, if there are, investigate them further.


### THE DELIVERABLES

My deliverables will include those required by the capstone project guidelines: code, a paper, and a slide deck. I may also record a video of me presenting the project's results.